 export const CREATE_ORDER_REQUEST="CREATE_ORDER_REQUEST";
 export const CREATE_ORDER_SUCCESS="CREATE_ORDER_sUCCESS";
 export const CREATE_ORDER_FAIL="CREATE_ORDER_FAIL";

 export const MY_ORDER_REQUEST="MY_ORDER_REQUEST";
 export const MY_ORDER_SUCCESS="MY_ORDER_SUCCESS";
 export const MY_ORDER_FAIL="MY_ORDER_FAIL";

 export const ORDER_DETAILS_REQUEST="ORDER_DETAILS_REQUEST";
 export const ORDER_DETAILS_SUCCESS="ORDER_DETAILS_SUCCESS";
 export const ORDER_DETAILS_FAIL="ORDER_DETAILS_FAIL";

 export const ADMIN_ALL_ORDERS="ADMIN_ALL_ORDERS";
 export const ADMIN_UPDATE_ORDER="ADMIN_UPDATE_ORDER";
 export const ADMIN_DELETE_ORDER="ADMIN_DELETE_ORDER";

 export const ALL_ORDER_ERROR="ALL_ORDER_ERROR"