export const ALL_PRODUCR_REQUEST="ALL_PRODUCT_REQUEST"
export const ALL_PRODUCT_SUCCESS="ALL_PRODUCT_SUCCESS"
export const ALL_PRODUCT_FAIL="ALL_PRODUCT_FAIL"

export const PRODUCT_DETAIL_REQUEST="PRODUCT_DETAIL_REQUEST";
export const PRODUCT_DETAIL_SUCCESS="PRODUCT_DETAIL_SUCCESS";
export const PRODUCT_DETAIL_FAIL="PRODUCT_DETAIL_FAIL"

export const ADMIN_ALL_PRODUCTS="ADMIN_ALL_PRODUCTS"