export const LOGIN_REQUEST="LOGIN_REQUEST";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_FAIL="LOGIN_FAIL";

export const SIGN_UP_REQUEST="LOGIN_REQUEST";
export const SIGN_UP_SUCCESS="LOGIN_SUCCESS";
export const SIGN_UP_FAIL="LOGIN_FAIL";


export const LOAD_REQUEST="LOAD_REQUEST";
export const LOAD_REQUEST_SUCCESS="LOAD_REQUEST_SUCCESS";
export const LOAD_REQUEST_FAIL="LOAD_USER_FAIL";

export const ADMIN_ALL_USERS="ADMIN_ALL_USERS";
export const ADMIN_DELETE_USER="ADMIN_DELETE_USER";
export const ADMIN_UPDATE_USER="ADMIN_UPDATE_USER";